### ISSUE TITLE
Quickslot Flyouts option does not function

### ISSUE THREAD

**Issue by Zautix** [GovtGeek/Outfitter#44]
Enabling the option and picking up an item from any slot produces this error:

Outfitter/OutfitterQuickSlots.lua:44: attempt to index global 'EquipmentFlyoutFrame' (a nil value)
[string "@Outfitter/OutfitterQuickSlots.lua"]:44: in function `PostClick'
[string "@Outfitter/OutfitterQuickSlots.lua"]:9: in function <Outfitter/OutfitterQuickSlots.lua:9>

Locals:
self = <table> {
 CurrentInventorySlot = "Trinket1Slot"
}
pButton = CharacterTrinket1Slot {
 subicon = CharacterTrinket1SlotSubIconTexture {
 }
 backgroundTextureName = 136528
 IconOverlay = Texture {
 }
 count = 1
 hasItem = 1
 checkRelic = false
 Count = CharacterTrinket1SlotCount {
 }
 IconBorder = Texture {
 }
 oGlowClassicBorder = Texture {
 }
 searchOverlay = CharacterTrinket1SlotSearchOverlay {
 }
 icon = CharacterTrinket1SlotIconTexture {
 }
}
vSlotItemLink = "|cffa335ee|Hitem:220634::::::::60:::::::::|h[Atal'ai Blood Ritual Charm]|h|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "|cffa335ee|Hitem:220634::::::::60:::::::::|h[Atal'ai Blood Ritual Charm]|h|r"
(*temporary) = "attempt to index global 'EquipmentFlyoutFrame' (a nil value)"

**Comment by GovtGeek** [comment]
What version are you using?

**Comment by Llamatron2112** [comment]
I use the version 4.4.1.2 on current SoD.

**Comment by GovtGeek** [comment]
4.4.1.4 should fix the issue. If so, please close this issue.

**Comment by Llamatron2112** [comment]
I can still see the option in the settings, and if I enable it I get an lua error when taking an item from its slot, and put it again. Not a big issue for sure, but it would be cleaner to disable the option in settings, and always set the preference to disabled.

**Comment by GovtGeek** [comment]
Are you sure you have 4.4.1.4? I just flipped it to production. It does actually remove the checkbox in classic.

**Comment by Llamatron2112** [comment]
Ha my bad, I had 4.4.1.3, it's all good in .4. Thanks for your work !
